version: "3.8"
networks:
    bot-network:
        driver: overlay

services:
    seq:
        image: datalust/seq:latest
        restart: always
        ports:
          - 444:80
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: '0.75'
                    memory: 200M
        networks:
            - bot-network
        environment:
            - ACCEPT_EULA=Y
    bot:
        image: ghcr.io/hirbod-codes/bot:latest
        ports:
          - 443:5001
        restart: always
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: '0.75'
                    memory: 200M
        networks:
            - bot-network
        environment:
            ASPNETCORE_ENVIRONMENT: Production
            ENVIRONMENT: Production
            SECRETS_PREFIX: BOT_
            BOT_Serilog__WriteTo__1__Args__serverUrl: http://seq:80
            BOT_MessageStoreName: InMemory
            BOT_BrokerName: Bingx
            BOT_RiskManagementName: SuperTrendV1
            BOT_IndicatorOptionsName: SuperTrendV1
            BOT_StrategyName: SuperTrendV1
            BOT_StrategyOptions__SuperTrendV1__ProviderName: SuperTrendV1
            BOT_BotName: SuperTrendV1
            BOT_RunnerName: SuperTrendV1
            BOT_NotifierName: NTFY
            BOT_PositionRepositoryName: InMemory
            BOT_MessageRepositoryName: InMemory
