version: "3.8"

services:
    seq:
        image: datalust/seq:latest
        ports:
          - 8081:80
        restart: always
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: '0.75'
                    memory: 200M
        environment:
            - ACCEPT_EULA=Y
    bot:
        build:
            context: ./
            dockerfile: ./src/bot/Dockerfile
            target: dev
        ports:
          - 443:5001
        depends_on:
            - seq
        restart: always
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: '0.75'
                    memory: 200M
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ENVIRONMENT: Development
            BOT_Serilog__WriteTo__1__Args__serverUrl: http://seq:80
            BOT_MessageStoreName: InMemory
            BOT_BrokerName: Bingx
            BOT_RiskManagementName: SuperTrendV1
            BOT_IndicatorOptionsName: SuperTrendV1
            BOT_StrategyName: SuperTrendV1
            BOT_StrategyOptions__SuperTrendV1__ProviderName: SuperTrendV1
            BOT_BotName: SuperTrendV1
            BOT_RunnerName: SuperTrendV1
            BOT_NotifierName: NTFY
            BOT_PositionRepositoryName: InMemory
            BOT_MessageRepositoryName: InMemory
