version: "3.8"
networks:
    bot-network:
        driver: overlay

services:
    seq:
        image: datalust/seq:latest
        restart: always
        ports:
          - 444:80
        environment:
            - ACCEPT_EULA=Y
        networks:
            - bot-network
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: '0.75'
                    memory: 200M
    bot:
        image: ghcr.io/hirbod-codes/bot:latest
        ports:
          - 443:443
        restart: always
        environment:
            Serilog__WriteTo__1__Args__serverUrl: http://seq:80
            USER_MANAGEMENT_ASPNETCORE_ENVIRONMENT: Production
            USER_MANAGEMENT_ENVIRONMENT: Production
        networks:
            - bot-network
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: '0.75'
                    memory: 200M
