version: "3.8"

networks:
    EMANetwork:
        driver: bridge
    UTNetwork:
        driver: bridge
  
services:
    ema_bot:
        container_name: ema_bot
        build:
            context: ./
            target: production
            dockerfile: ./src/bot/Dockerfile
        environment:
            StrategyName: EMA
            EMAStrategy:Serilog:WriteTo:1:Args:serverUrl: http://ema_seq:80
    ema_seq:
        image: datalust/seq:5.1
        ports:
          - 8081:80
        environment:
            - ACCEPT_EULA=Y
        volumes:
          - ./src/bot/EMALogs:/data:rw
    ut_bot:
        container_name: ut_bot
        build:
            context: ./
            target: production
            dockerfile: ./src/bot/Dockerfile
        environment:
            StrategyName: UT
            UTStrategy:Serilog:WriteTo:1:Args:serverUrl: http://ut_seq:80
    ut_seq:
        image: datalust/seq:5.1
        ports:
          - 8080:80
        environment:
            - ACCEPT_EULA=Y
        volumes:
          - ./src/bot/UTLogs:/data:rw
