FROM mcr.microsoft.com/dotnet/sdk:7.0

WORKDIR /app

COPY ./trading_bot.sln ./
COPY ./src/bot/bot.csproj ./src/bot/
COPY ./src/StrategyTester/StrategyTester.csproj ./src/StrategyTester/
COPY ./Tests/unit_tests/unit_tests.csproj ./Tests/unit_tests/
COPY ./Tests/manual_tests/manual_tests.csproj ./Tests/manual_tests/

RUN dotnet restore -f --force-evaluate -v d

COPY ./src/ ./src/

WORKDIR /app/src/bot/

RUN dotnet publish --no-restore -c Release -o /publish

WORKDIR /publish

CMD dotnet bot.dll 
