sudo docker build --tag ghcr.io/hirbod-codes/bot:latest_win_x64 --target win_x64 -f src/bot/Dockerfile.production .
sudo docker build --tag ghcr.io/hirbod-codes/bot:latest_win_x86 --target win_x86 -f src/bot/Dockerfile.production .
sudo docker build --tag ghcr.io/hirbod-codes/bot:latest_win_arm64 --target win_arm64 -f src/bot/Dockerfile.production .
sudo docker build --tag ghcr.io/hirbod-codes/bot:latest_linux_x64 --target linux_x64 -f src/bot/Dockerfile.production .
sudo docker build --tag ghcr.io/hirbod-codes/bot:latest_linux_musl_x64 --target linux_musl_x64 -f src/bot/Dockerfile.production .
sudo docker build --tag ghcr.io/hirbod-codes/bot:latest_linux_musl_arm64 --target linux_musl_arm64 -f src/bot/Dockerfile.production .
sudo docker build --tag ghcr.io/hirbod-codes/bot:latest_linux_arm --target linux_arm -f src/bot/Dockerfile.production .
sudo docker build --tag ghcr.io/hirbod-codes/bot:latest_linux_arm64 --target linux_arm64 -f src/bot/Dockerfile.production .
sudo docker build --tag ghcr.io/hirbod-codes/bot:latest_linux_bionic_arm64 --target linux_bionic_arm64 -f src/bot/Dockerfile.production .
sudo docker build --tag ghcr.io/hirbod-codes/bot:latest_osx_x64 --target osx_x64 -f src/bot/Dockerfile.production .
sudo docker build --tag ghcr.io/hirbod-codes/bot:latest_osx_arm64 --target osx_arm64 -f src/bot/Dockerfile.production .
sudo docker build --tag ghcr.io/hirbod-codes/bot:latest_ios_arm64 --target ios_arm64 -f src/bot/Dockerfile.production .
sudo docker build --tag ghcr.io/hirbod-codes/bot:latest_android_arm64 --target android_arm64 -f src/bot/Dockerfile.production .
